// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from decoder.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace decoder {

class Decoder {
public:
    virtual ~Decoder() {}

    /** create() is to create an instance of the decoder */
    static std::shared_ptr<Decoder> create();

    virtual std::string decode(int8_t* image) = 0;

    virtual std::string decodeWithAngles(int8_t* image, const std::vector<int32_t> & xInputQuad, const std::vector<int32_t> & yInputQuad) = 0;
};

}  // namespace decoder
