// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from decoder.djinni

#pragma once

#include <stdint.h>
#include <cstdint>
#include <memory>
#include <string>

namespace decoder {

class Decoder {
public:
    virtual ~Decoder() {}

    /** create() is to create an instance of the decoder */
    static std::shared_ptr<Decoder> create();

    /** getters-setters */
    virtual int8_t* getImage() = 0;

    virtual void setImage(int8_t* image, int32_t rows, int32_t cols, int32_t type) = 0;

    virtual void setXInputQuad(int32_t xQuad) = 0;

    virtual void setYInputQuad(int32_t yQuad) = 0;

    virtual void seXOutputQuad(int32_t xQuad) = 0;

    virtual void setYOutputQuad(int32_t yQuad) = 0;

    virtual int8_t* perspectiveTransform() = 0;
};

}  // namespace decoder
